### ISSUE TITLE
Minor: debug binaries are stripped in fixes-24

### ISSUE THREAD

**Issue by Floppe** [MarcT/mt-mythtv#13]
Seems like the binaries are stripped although DEBUG use flag is set.
# file /usr/bin/mythcommflag

/usr/bin/mythcommflag: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.9, stripped

**Comment by MarcT** [comment]
This is done because of your feature settings in your make file and not as a result of the ebuild itself. Add nostrip or splitdebug to your FEATURES in /etc/make.conf.
For more information on which feature setting you want to use please review the information on the following page. http://www.gentoo.org/proj/en/qa/backtraces.xml

**Comment by Floppe** [comment]
Oh, I thought it was up to the ebuild.

I made a file called /etc/portage/env/media-tv/mythtv-9999 and added nostrip to features as I don't want my whole system to have unstripped binaries. Thanks.
