### ISSUE TITLE
MythWeather dependencies that maybe would could go into the ebuild

### ISSUE THREAD

**Issue by Floppe** [MarcT/mt-mythtv#4]
Not really an issue, but an enhancement.

MythWeather now depends on the following two ebuilds too before it builds.

dev-perl/XML-XPath
dev-perl/DateTime-Format-ISO8601 [masked]
dev-perl/DateTime-Format-Builder [masked]
dev-perl/DateTime-Format-Strptime [masked]

// Floppe

**Comment by MarcT** [comment]
dev-perl/XML-XPath I discovered last night, I just had not pushed up yet, its up now.
dev-perl/DateTime-Format-ISO8601 is already in there, has been since r96.
dev-perl/DateTime-Format-Strptime is a dependency of dev-perl/DateTime-Format-ISO8601, no need to add it here too.
dev-perl/DateTime-Format-Builder is a dependency of dev-perl/DateTime-Format-Strptime, no need to add it here too.
